### ISSUE TITLE
Access problem: Error due to IP address switch

### ISSUE THREAD

**Issue by Gezzo42** [hthiery/python-fritzhome#92]
I recently changed my Homeassistant hardware. Afterwards I was not able to use the FRITZ!SmartHome integration. I got the following error:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://fritz.box/webservices/homeautoswitch.lua?switchcmd=gettemplatelistinfos&sid=88a3e4bb76d62fe0`
The Fritz!Box reports an failed log in. Tests with the CLI results in the same error, but not on my normal PC. It seems to be similar to the problem of the following [report](https://github.com/home-assistant/core/issues/83987).
Further investigation using wireshard revealed the problem:
![grafik](https://github.com/hthiery/python-fritzhome/assets/31780740/b80b79e2-6819-492b-8ec5-9e3bf62ba2c8)
The used IPv6 address changed between the different request and the address needs to be the same, otherwise the request failes.
My first idea was to get the source IP address of the first request and set it for further connections. But getting the source address is tricky and did not work with the Fritz!Box ([further information](https://stackoverflow.com/questions/22492484/how-do-i-get-the-ip-address-from-a-http-request-using-the-requests-library)).
I came up with the following quick and dirty solution in `fritzhome.py`:
```
import requests
requests.packages.urllib3.util.connection.HAS_IPV6 = False
```
Do you have an idea for a better solution? Especially for integration into pyfritzhome.

Some background on the environment: Raspberry Pi OS Lite 64 based on Debian 12 with the IP addresses assigned via DHCP.

**Comment by mib1185** [comment]
there is a known bug with IPv6 and link local address in the pythons request module (https://github.com/python/cpython/issues/73561). it should be fixed in upcoming release of python 3.11 and 3.12

**Comment by Gezzo42** [comment]
Thanks for the link. I will test it.

**Comment by Gezzo42** [comment]
I solved the problem for me by forcing to use IPv4 in the file _fritzhome.py_:
`import requests
requests.packages.urllib3.util.connection.HAS_IPV6 = False`

I wanted to update to a newer Homeassistant version and therefore tested, if I still get the same problem with the newer python-fritzhome version. But it works now, also the IPv6 address still changes during the request. Either there is a complete different problem or an update of the Fritzbox fixed the problem.
